### ISSUE TITLE
DOM element does not get removed

### ISSUE THREAD

**Issue by christophmayrhofer** [gwendall/meteor-template-animations#8]
First of all thanks for the package.. However there seems to be a slight problem with the item removal:
The animation gets trigger correctly, but the DOM element does not get deleted after the remove animation. It's final state is the following:

``` html
<li class="task inserting removing fade-out" style="opacity: 1; transition: all 0s ease 0s; background-color: rgba(235, 113, 113, 0.498039);">
```

My JS code (I also noticed that remove: after: does not get triggered):

``` javascript
Template.tasks.animations({
    ".task": {
        container: ".taskList", // container of the ".item" elements
        insert: {
            class: "fade-in", // class applied to inserted elements
            delay: 500 // Delay before inserted items animate
        },
        remove: {
            class: "fade-out", // class applied to removed elements
            delay: 500, // Delay before removed items animate
            after: function(attrs, element, template) {console.log(element);} 
        },
    }
});
```

and the css:

``` css
.fade-in{
    opacity:1 !important;
    transition: opacity 2s ease !important;
}

.fade-out{
    opacity:0 !important;
    transition: opacity 2s ease !important;
}
```
